### ISSUE TITLE
Support command "TTL"

### ISSUE THREAD

**Issue by pjeziorowski** [Qovery/RedisLess#22]
Returns the remaining time to live of a key that has a timeout. This introspection capability allows a Redis client to check how many seconds a given key will continue to be part of the dataset.

In Redis 2.6 or older the command returns -1 if the key does not exist or if the key exist but has no associated expire.

Starting with Redis 2.8 the return value in case of error changed:

    The command returns -2 if the key does not exist.
    The command returns -1 if the key exists but has no associated expire.

**Comment by barkanido** [comment]
Hey, wanted to help here. we the first step, I am thinking about adding `storage::Storage` trait a method called `meta`: 
```rust
fn meta(&self, key: &[u8]) -> Option<meta::RedisMeta>
```
it should return the TTL and the type, and serve both the TYPE and the TTL commands. possibly, other internal implementations that need either expiry or type.

WDYT?

**Comment by evoxmusic** [comment]
Can you propose a full implementation of meta?

**Comment by barkanido** [comment]
there is already a partial implementation in storage/modes/meta, since both `data_type` and `expiry` are public, I think it should be enough for now. It may grow in the future.

**Comment by clarity0** [comment]
If you are gonna do ttl, I think itd be better to change Expiry from how it's currrently implemented with an `Instant` to use timestamps. TTL is doable with `Instant` but other commands like `expireat` and `pexpireat` take unix timestamps. And it's not doable with Instant afaik

**Comment by barkanido** [comment]
@clarity0 I am trying to picture the flow of `TTL`, `expireat` and `pexpireat` with the _current_ implementation using `Instatnt`.
* `TTL` => if instant.now() <= expiry.timestamp => -1, if key is missing, -2, else just `now() - expiry.timestamp()`.
* `PTTL` => same but in millis.
* `EXPIREAT(timestamp)`=> parse timestamp to `NaiveDateTime` (should we use [Chrono](https://docs.rs/chrono/0.4.19/chrono/naive/struct.NaiveDateTime.html#method.from_timestamp_opt)?) compute the duration from now and update the current instant.

Is that a problem?
using `Instant` has the advantage of both be monotonically increasing and avoid as many system calls in reading the clock.

**Comment by clarity0** [comment]
But afaik, there is no way to go from an [Instant](https://doc.rust-lang.org/std/time/struct.Instant.html) to a unix timestamp. I think it would be better to use chrono for this, in particular with this method [timestamp_millis](https://docs.rs/chrono/0.4.19/chrono/struct.DateTime.html#method.timestamp_millis), since the [redis specification](https://redis.io/commands/expire) wants expires to be precise to at least 1ms. 

>Expires and persistence
>
>Keys expiring information is stored as absolute Unix timestamps (in milliseconds in case of Redis version 2.6 or greater).This means that the time is flowing even when the Redis instance is not active.

**Comment by barkanido** [comment]
@clarity0 see above PR to set prepare for solving this issue.

**Comment by barkanido** [comment]
going forward I am thinking about a proper way to extend the `Storage` trait.

first, add:
```rust
    fn meta(&self, key: &[u8])-> Option<&RedisMeta>; //can be also &mut self if we want to do GC same as done during read
```
this can support `ttl`, `pttl`, `type`...

another option is to add:
```rust
    fn expiry(&self, key: &[u8])-> Option<&Expiry>; //same comment about mutbility as above
    fn type(&self, key: &[u8])-> Option<RedisType>;

```

adding `meta` is currently more useful but only because of the way metadata bookkeeping is implemented in the `InMemoryStorage`. Other types of storage might split expiry from type as an example. Adding separate `expiry` and `type` methods is narrower, hence a bit more resilient for future implementations.

**Comment by barkanido** [comment]
@clarity0 pushed a PR that goes with the first option. tell me what you think.
